# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt
#
# Tell Travis what to do
# https://travis-ci.com/nedbat/coveragepy

dist: xenial
language: python

cache: pip

# https://docs.travis-ci.com/user/languages/python/#python-versions
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'pypy2.7-7.3.1'
  - 'pypy3.6-7.3.1'

# Only testing it for python3.8 on aarch64 platform, since it already has a lot
# of jobs to test and takes long time.
matrix:
  include:
    - python: 3.8
      arch: arm64
      env:
        - COVERAGE_COVERAGE=no
    - python: 3.8
      arch: arm64
      env:
        - COVERAGE_COVERAGE=yes

env:
  matrix:
    - COVERAGE_COVERAGE=no
    - COVERAGE_COVERAGE=yes

install:
  - pip install -r requirements/ci.pip
  - pip freeze

script:
  - tox

after_script:
  - |
    if [[ $COVERAGE_COVERAGE == 'yes' ]]; then
      python igor.py combine_html
      pip install codecov
      codecov -X gcov --file coverage.xml
    fi
