# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt

name: "Test Suite"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "pypy3"]
        exclude:
          # Windows PyPy doesn't seem to work?
          - os: windows-latest
            python-version: "pypy3"
      fail-fast: false

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install Visual C++ for Python 2.7"
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: "Install dependencies"
        shell: bash
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install -r requirements/ci.pip
          python -m pip install -c requirements/pins.pip tox-gh-actions

      - name: "Run tox for ${{ matrix.python-version }}"
        shell: bash
        continue-on-error: true
        id: tox1
        run: |
          python -m tox

      - name: "Retry tox for ${{ matrix.python-version }}"
        shell: bash
        id: tox2
        if: steps.tox1.outcome == 'failure'
        run: |
          python -m tox

      - name: "Set status"
        shell: bash
        if: always()
        run: |
          if ${{ steps.tox1.outcome == 'success' || steps.tox2.outcome == 'success' }}; then
             echo success
          else
             exit 1
          fi
